// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team.sql

package db

import (
	"context"
	"time"
)

const createTeamMembership = `-- name: CreateTeamMembership :one
INSERT INTO team_memberships (user_id, team_id, role)
VALUES ($1, $2, $3)
RETURNING id, team_id, user_id, role, joined_at
`

type CreateTeamMembershipParams struct {
	UserID int32        `json:"user_id"`
	TeamID int32        `json:"team_id"`
	Role   TeamUserRole `json:"role"`
}

func (q *Queries) CreateTeamMembership(ctx context.Context, arg CreateTeamMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, createTeamMembership, arg.UserID, arg.TeamID, arg.Role)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getTeamByDomain = `-- name: GetTeamByDomain :one
SELECT id, name, domain, created_at FROM teams WHERE domain = $1
`

func (q *Queries) GetTeamByDomain(ctx context.Context, domain string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByDomain, domain)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamMembershipByUserID = `-- name: GetTeamMembershipByUserID :one
SELECT id, team_id, user_id, role, joined_at FROM team_memberships WHERE user_id = $1 AND team_id = $2
`

type GetTeamMembershipByUserIDParams struct {
	UserID int32 `json:"user_id"`
	TeamID int32 `json:"team_id"`
}

func (q *Queries) GetTeamMembershipByUserID(ctx context.Context, arg GetTeamMembershipByUserIDParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, getTeamMembershipByUserID, arg.UserID, arg.TeamID)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getTeamsByUserID = `-- name: GetTeamsByUserID :many
SELECT
  t.id AS team_id,
  t.name AS team_name,
  t.domain AS team_domain,
  tm.id AS membership_id,
  tm.role AS user_role,
  tm.joined_at AS user_joined_at
  FROM teams t
  INNER JOIN team_memberships tm ON t.id = tm.team_id
  WHERE tm.user_id = $1
`

type GetTeamsByUserIDRow struct {
	TeamID       int32        `json:"team_id"`
	TeamName     string       `json:"team_name"`
	TeamDomain   string       `json:"team_domain"`
	MembershipID int32        `json:"membership_id"`
	UserRole     TeamUserRole `json:"user_role"`
	UserJoinedAt time.Time    `json:"user_joined_at"`
}

func (q *Queries) GetTeamsByUserID(ctx context.Context, userID int32) ([]GetTeamsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getTeamsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamsByUserIDRow
	for rows.Next() {
		var i GetTeamsByUserIDRow
		if err := rows.Scan(
			&i.TeamID,
			&i.TeamName,
			&i.TeamDomain,
			&i.MembershipID,
			&i.UserRole,
			&i.UserJoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
