// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (user_id, provider, provider_account_id, password) VALUES ($1, $2, $3, $4) RETURNING id, user_id, provider, provider_account_id, password, created_at, updated_at
`

type CreateAccountParams struct {
	UserID            int32  `json:"user_id"`
	Provider          string `json:"provider"`
	ProviderAccountID string `json:"provider_account_id"`
	Password          []byte `json:"password"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.Provider,
		arg.ProviderAccountID,
		arg.Password,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAccountsByID = `-- name: GetUserAccountsByID :many
SELECT id, user_id, provider, provider_account_id, password, created_at, updated_at FROM accounts WHERE user_id = $1
`

func (q *Queries) GetUserAccountsByID(ctx context.Context, userID int32) ([]Account, error) {
	rows, err := q.db.Query(ctx, getUserAccountsByID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderAccountID,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
