// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tag.sql

package db

import (
	"context"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (team_id, name, data_type) VALUES ($1, $2, $3) RETURNING id, team_id, name, data_type, created_at
`

type CreateTagParams struct {
	TeamID   int32       `json:"team_id"`
	Name     string      `json:"name"`
	DataType TagDataType `json:"data_type"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.TeamID, arg.Name, arg.DataType)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.DataType,
		&i.CreatedAt,
	)
	return i, err
}

const createTagValue = `-- name: CreateTagValue :one
INSERT INTO tag_values (tag_id, value) VALUES ($1, $2) RETURNING id, tag_id, value, created_at
`

type CreateTagValueParams struct {
	TagID int32  `json:"tag_id"`
	Value string `json:"value"`
}

func (q *Queries) CreateTagValue(ctx context.Context, arg CreateTagValueParams) (TagValue, error) {
	row := q.db.QueryRow(ctx, createTagValue, arg.TagID, arg.Value)
	var i TagValue
	err := row.Scan(
		&i.ID,
		&i.TagID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :one
DELETE FROM tags WHERE id = $1 RETURNING id, team_id, name, data_type, created_at
`

func (q *Queries) DeleteTag(ctx context.Context, id int32) (Tag, error) {
	row := q.db.QueryRow(ctx, deleteTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.DataType,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTagValue = `-- name: DeleteTagValue :one
DELETE FROM tag_values WHERE id = $1 RETURNING id, tag_id, value, created_at
`

func (q *Queries) DeleteTagValue(ctx context.Context, id int32) (TagValue, error) {
	row := q.db.QueryRow(ctx, deleteTagValue, id)
	var i TagValue
	err := row.Scan(
		&i.ID,
		&i.TagID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const listTagValues = `-- name: ListTagValues :many
SELECT id, tag_id, value, created_at FROM tag_values WHERE tag_id = $1
`

func (q *Queries) ListTagValues(ctx context.Context, tagID int32) ([]TagValue, error) {
	rows, err := q.db.Query(ctx, listTagValues, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TagValue
	for rows.Next() {
		var i TagValue
		if err := rows.Scan(
			&i.ID,
			&i.TagID,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, team_id, name, data_type, created_at FROM tags WHERE team_id = $1
`

func (q *Queries) ListTags(ctx context.Context, teamID int32) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.DataType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags SET name = $2, data_type = $3 WHERE id = $1 RETURNING id, team_id, name, data_type, created_at
`

type UpdateTagParams struct {
	ID       int32       `json:"id"`
	Name     string      `json:"name"`
	DataType TagDataType `json:"data_type"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.ID, arg.Name, arg.DataType)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.DataType,
		&i.CreatedAt,
	)
	return i, err
}
