// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeamMembership = `-- name: CreateTeamMembership :one
INSERT INTO team_memberships (user_id, team_id, role)
VALUES ($1, $2, $3)
RETURNING id, team_id, user_id, role, joined_at
`

type CreateTeamMembershipParams struct {
	UserID int32        `json:"user_id"`
	TeamID int32        `json:"team_id"`
	Role   TeamUserRole `json:"role"`
}

func (q *Queries) CreateTeamMembership(ctx context.Context, arg CreateTeamMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, createTeamMembership, arg.UserID, arg.TeamID, arg.Role)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getTeamByDomain = `-- name: GetTeamByDomain :one
SELECT id, name, domain, created_at FROM teams WHERE domain = $1
`

func (q *Queries) GetTeamByDomain(ctx context.Context, domain string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByDomain, domain)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamProfileByUserID = `-- name: GetTeamProfileByUserID :one
SELECT
  t.id AS team_id,
  t.name AS team_name,
  tm.role AS user_role,
  t.created_at AS team_created_at
  FROM teams t
  INNER JOIN team_memberships tm ON t.id = tm.team_id
  WHERE tm.user_id = $1
  LIMIT 1
`

type GetTeamProfileByUserIDRow struct {
	TeamID        int32            `json:"team_id"`
	TeamName      string           `json:"team_name"`
	UserRole      TeamUserRole     `json:"user_role"`
	TeamCreatedAt pgtype.Timestamp `json:"team_created_at"`
}

func (q *Queries) GetTeamProfileByUserID(ctx context.Context, userID int32) (GetTeamProfileByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getTeamProfileByUserID, userID)
	var i GetTeamProfileByUserIDRow
	err := row.Scan(
		&i.TeamID,
		&i.TeamName,
		&i.UserRole,
		&i.TeamCreatedAt,
	)
	return i, err
}
