// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upload.sql

package db

import (
	"context"
	"time"
)

const createDocRef = `-- name: CreateDocRef :one
INSERT INTO doc_refs (doc_id, team_id, user_id, file_name)
VALUES ($1, $2, $3, $4)
RETURNING id, doc_id, user_id, team_id, file_name, created_at
`

type CreateDocRefParams struct {
	DocID    int32  `json:"doc_id"`
	TeamID   int32  `json:"team_id"`
	UserID   int32  `json:"user_id"`
	FileName string `json:"file_name"`
}

func (q *Queries) CreateDocRef(ctx context.Context, arg CreateDocRefParams) (DocRef, error) {
	row := q.db.QueryRow(ctx, createDocRef,
		arg.DocID,
		arg.TeamID,
		arg.UserID,
		arg.FileName,
	)
	var i DocRef
	err := row.Scan(
		&i.ID,
		&i.DocID,
		&i.UserID,
		&i.TeamID,
		&i.FileName,
		&i.CreatedAt,
	)
	return i, err
}

const createDocRefTags = `-- name: CreateDocRefTags :exec
INSERT INTO doc_ref_tags (doc_ref_id, key_id, value_id)
VALUES ($1, $2, $3)
`

type CreateDocRefTagsParams struct {
	DocRefID int32 `json:"doc_ref_id"`
	KeyID    int32 `json:"key_id"`
	ValueID  int32 `json:"value_id"`
}

func (q *Queries) CreateDocRefTags(ctx context.Context, arg CreateDocRefTagsParams) error {
	_, err := q.db.Exec(ctx, createDocRefTags, arg.DocRefID, arg.KeyID, arg.ValueID)
	return err
}

const deleteAllDocRefTags = `-- name: DeleteAllDocRefTags :exec
DELETE FROM doc_ref_tags WHERE doc_ref_id = $1
`

func (q *Queries) DeleteAllDocRefTags(ctx context.Context, docRefID int32) error {
	_, err := q.db.Exec(ctx, deleteAllDocRefTags, docRefID)
	return err
}

const getDoc = `-- name: GetDoc :one
SELECT id, storage_key, file_sha256, file_size, file_mime_type, status, created_at
FROM docs
WHERE docs.id = $1
`

func (q *Queries) GetDoc(ctx context.Context, id int32) (Doc, error) {
	row := q.db.QueryRow(ctx, getDoc, id)
	var i Doc
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.FileSha256,
		&i.FileSize,
		&i.FileMimeType,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getOrCreateDoc = `-- name: GetOrCreateDoc :one
INSERT INTO docs (storage_key, file_sha256, file_size, file_mime_type)
VALUES ($1, $2, $3, $4)
ON CONFLICT (file_sha256, file_size) DO UPDATE SET storage_key = docs.storage_key
RETURNING id, storage_key, file_sha256, file_size, file_mime_type, status, created_at, (xmax = 0) as created
`

type GetOrCreateDocParams struct {
	StorageKey   string `json:"storage_key"`
	FileSha256   string `json:"file_sha256"`
	FileSize     int64  `json:"file_size"`
	FileMimeType string `json:"file_mime_type"`
}

type GetOrCreateDocRow struct {
	ID           int32         `json:"id"`
	StorageKey   string        `json:"storage_key"`
	FileSha256   string        `json:"file_sha256"`
	FileSize     int64         `json:"file_size"`
	FileMimeType string        `json:"file_mime_type"`
	Status       DocProcStatus `json:"status"`
	CreatedAt    time.Time     `json:"created_at"`
	Created      bool          `json:"created"`
}

func (q *Queries) GetOrCreateDoc(ctx context.Context, arg GetOrCreateDocParams) (GetOrCreateDocRow, error) {
	row := q.db.QueryRow(ctx, getOrCreateDoc,
		arg.StorageKey,
		arg.FileSha256,
		arg.FileSize,
		arg.FileMimeType,
	)
	var i GetOrCreateDocRow
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.FileSha256,
		&i.FileSize,
		&i.FileMimeType,
		&i.Status,
		&i.CreatedAt,
		&i.Created,
	)
	return i, err
}

const updateDocStatus = `-- name: UpdateDocStatus :exec
UPDATE docs SET status = $2 WHERE id = $1
`

type UpdateDocStatusParams struct {
	ID     int32         `json:"id"`
	Status DocProcStatus `json:"status"`
}

func (q *Queries) UpdateDocStatus(ctx context.Context, arg UpdateDocStatusParams) error {
	_, err := q.db.Exec(ctx, updateDocStatus, arg.ID, arg.Status)
	return err
}
